spring.application.name=demo

# default profile for local/dev usage
spring.profiles.active=dev

# shared defaults
server.servlet.context-path=/mealplanner
server.address=0.0.0.0
server.port=8080

spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=false
spring.flyway.enabled=false

logging.level.root=INFO
logging.level.com.example.demo=INFO
logging.level.org.springframework.security=INFO

app.security.require-secrets=false
